
CREATE PROCEDURE REF
    @Refcode NVARCHAR(255)
AS
BEGIN
    SELECT ID, USR, REFCODE,INVOICEDATE,PYMTORDNUM,PAYERNIPT,NIVF,PAIDAMT,PAIDCUR,TRANSACTIONCODE,PYMTTYPE,SELLERNIPT
    FROM Fiscal
    WHERE Refcode = @Refcode;
END
